/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lordstephen77' at '20/06/17 13.50' with Gradle 2.14.1
 *
 * @author lordstephen77, @date 20/06/17 13.50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
